### ISSUE TITLE
GetBalance, err: Method not found

### ISSUE THREAD

**Issue by ygcool** [nervosnetwork/ckb-sdk-go#61]
```
	apic, err := api.NewCkbApi("https://ckb-mainnet.rebase.network/indexer")
	if err != nil {
		panic(err)
	}
	builder := model.NewGetBalancePayloadBuilder()
	builder.AddAddress("ckb1qyqzy2x6udq0tpmywd3dx83lqnt628updrwqfdartc")
	builder.AddAssetInfo(common.NewCkbAsset())
	balance, err := apic.GetBalance(builder.Build())
	if err != nil {
		panic(err)
	}
	fmt.Println(balance)
	marshal, _ := json.Marshal(balance)
	fmt.Println(string(marshal))
```

**Comment by zhengjianhui** [comment]
You should run a mercury server instead of an indexer server. Because GetBalance is a RPC method of mercury.
You can follow the documentation to [run mercury v0.2.0-beta.1](https://github.com/nervosnetwork/mercury#running-mercury-development-environment)
Then use ckb-sdk-go v0.43.3-beta.1, and refer to the [RPC example](https://github.com/nervosnetwork/ckb-sdk-go#example-1)

**Comment by zhengjianhui** [comment]
> ```
> 	apic, err := api.NewCkbApi("https://ckb-mainnet.rebase.network/indexer")
> 	if err != nil {
> 		panic(err)
> 	}
> 	builder := model.NewGetBalancePayloadBuilder()
> 	builder.AddAddress("ckb1qyqzy2x6udq0tpmywd3dx83lqnt628updrwqfdartc")
> 	builder.AddAssetInfo(common.NewCkbAsset())
> 	balance, err := apic.GetBalance(builder.Build())
> 	if err != nil {
> 		panic(err)
> 	}
> 	fmt.Println(balance)
> 	marshal, _ := json.Marshal(balance)
> 	fmt.Println(string(marshal))
> ```

You should run a mercury server instead of an indexer server. Because GetBalance is a RPC method of mercury.
You can follow the documentation to [run mercury v0.2.0-beta.1](https://github.com/nervosnetwork/mercury#running-mercury-development-environment)
Then use ckb-sdk-go v0.43.3-beta.1, and refer to the [RPC example](https://github.com/nervosnetwork/ckb-sdk-go#example-1)
